language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t mrsouliner/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true mrsouliner/react-test npm test

after_success:
  - docker build -t mrsouliner/multi-client ./client 
  - docker build -t mrsouliner/multi-nginx ./nginx
  - docker build -t mrsouliner/multi-server ./server
  - docker build -t mrsouliner/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
  - docker push mrsouliner/multi-client
  - docker push mrsouliner/multi-nginx
  - docker push mrsouliner/multi-server
  - docker push mrsouliner/multi-worker
